Version 0
SymbolType BLOCK
PIN 0 -16 NONE 8
PINATTR PinName IN+
PINATTR SpiceOrder 1
PIN -16 0 NONE 8
PINATTR PinName IN-
PINATTR SpiceOrder 2
PIN 0 16 NONE 8
PINATTR PinName Vcc
PINATTR SpiceOrder 3
PIN 16 0 NONE 8
PINATTR PinName GND
PINATTR SpiceOrder 4
PIN 16 -16 NONE 8
PINATTR PinName OUT
PINATTR SpiceOrder 5
